# Generated by Django 5.0.4 on 2024-05-03 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticket_number_alter_ticket_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', [1, 2])), fields=('user', 'queue'), name='unique_user_queue_for_new_or_in_progress'),
        ),
    ]
