# Generated by Django 5.0.4 on 2024-05-03 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ticket_unique_user_queue_for_new_or_in_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_user_queue_for_new_or_in_progress',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', [1, 2])), fields=('user', 'queue'), name='unique_user_queue_for_new_or_in_progress'),
        ),
    ]
